spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
queue:
  pedido-gerado: queue-pedido-gerado
  pedido-aprovado: queue-pedido-aprovado
  in:
    retorno-pagamento: queue-retorno-pagamento