# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Save artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: pedido-valhalla-artifact
          path: target/api.pedido.valhalla.kitchen-1.0.0.jar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: |
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            SPRING_PROFILE=${{ secrets.SPRING_PROFILE }}
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-pedidos-valhalla-kitchen:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install openssh-client -y
      - name: Connect into EC2 Instance and start container
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.HOST_DNS}}
        run: |
          echo "$EC2_SSH_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOSTNAME} '
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/api-pedidos-valhalla-kitchen
            docker rm -f api-pedidos-valhalla-kitchen
            docker run -d -p 8080:8080 --name api-pedidos-valhalla-kitchen ${{ secrets.DOCKERHUB_USERNAME }}/api-pedidos-valhalla-kitchen
          '
